name: Build and Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            LIBCLANG_PATH: '/usr/lib/'

        steps:
        - uses: actions/checkout@v3

        - name: Install LLVM
          run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 15 && sudo ln -fs "$(which llvm-config-15)" /usr/bin/llvm-config && sudo ln -fs "$(find $(llvm-config --libdir) -mindepth 1 -maxdepth 1 -name libclang.so.* -type l)" /usr/lib/libclang.so

        - name: Build
          run: cargo build
        - name: Clippy
          run: cargo clippy -- -Dwarnings -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used
        - name: Formatting
          run: cargo fmt --check
